### ISSUE TITLE
Make body configurable

### ISSUE THREAD

**Issue by timheuer** [craigloewen-msft/GitGudSimilarIssues#23]
Right now the body message is hard-coded.  Provide a default, but make it configurable as an input to the action

**Comment by craigloewen-msft** [comment]
Fixed by adding a 'commentbody' input! Thank you for the suggestion.

https://github.com/craigloewen-msft/GitGudSimilarIssues/blob/31ca2bdeece539a74f42fb0a9e4c25c71bf3627a/.github/workflows/newissuesworkflow.yml#L17C7-L17C25
