### ISSUE TITLE
If the bot doesn't find a similar issue, the action reports an error

### ISSUE THREAD

**Issue by zadjii-msft** [craigloewen-msft/GitGudSimilarIssues#32]
From https://github.com/microsoft/terminal/issues/16402

It correctly does nothing, and that's all good. But I agree, finding no similar issues isn't really an _error_ state, it's a `S_FALSE` state.

**Comment by craigloewen-msft** [comment]
Fixed! https://github.com/craigloewen-msft/GitGudSimilarIssues/commit/b90df4f9528635a69b068a78dd25e6569a3f2107
